host: 0.0.0.0
port: 8088
server: http://localhost

theme: custom

globalVariables:
  defaultLanguage: en
  supportLanguages: # use value in i18n.js
    - en
    - zh-hans
    - ko-kr
    - tr-tr
    - ru
