host: 0.0.0.0
port: 8088
server: http://localhost
cosApiUrl: https://localhost:4443/api
cosApiTokenUsername: admin
cosApiTokenPassword: admin

theme: default

globalVariables:
  defaultLanguage: en
  supportLanguages: # use value in i18n.js
    - en
    - zh-hant
    - zh-hans
    - ko-kr
    - ru
